# Generated by Django 5.1.6 on 2025-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_ticket_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="sentiment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
